doctrine_migrations:
    migrations_paths:
        # namespace is arbitrary but should be different from App\Migrations
        # as migrations classes should NOT be autoloaded
        # php bin/console doctrine:migrations:execute --up 'Application\Migrations\Version20220624150329'
        Application\Migrations: '%kernel.project_dir%/migrations'
    enable_profiler: '%kernel.debug%'
